[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ah_openrouter"
version = "1.0.0"
authors = [
  { name = "AH" }
]
description = "OpenRouter API integration service"
requires-python = ">=3.8"
dependencies = [
    "openai",
    "termcolor"
]
